### ISSUE TITLE
Update slides link

### ISSUE THREAD

**Issue by JulieKuehl** [wptrainingteam/theme-customizer-user#7]
The link to the slides is going to a 404. It should be updated to the current location (if needed).

**Comment by jessecowens** [comment]
@zappmatic

**Comment by zappmatic** [comment]
done.

**Comment by JulieKuehl** [comment]
This is still going to a 404 page. Perhaps the GitHub Page cron job update has not yet happened?

**Comment by zappmatic** [comment]
Right, there still is a 404. 

According to @jessecowens the URL is now correct. It will work als soon as the slides move from the /dev/ - part to the production part of the server. 

The templates are here: https://wptrainingteam.github.io/dev/lesson-plan/theme-customizer-user/slides/  - but it makes no sense to point to /dev/ part, since it will not be correct at production time.

What will be the next step? Creating the Slides in /dev/ or copying the empty template-slides to the production url? (And how is this done?)

**Comment by JulieKuehl** [comment]
I think the next step is for me to pull the dev branch into the master branch. Done! Thank you for pointing that out.
